# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container
COPY ./src .
COPY ./requirements_streamlit.txt ./requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose Streamlit's default port (8501)
EXPOSE 8501

# Command to run Streamlit
CMD ["streamlit", "run", "streamlit_app.py"]
