services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: test-fastapi-pdp
    ports:
      - "8000:8000"
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: test-streamlit-pdp
    ports:
      - "8501:8501"
    depends_on:
      - fastapi  # Ensures FastAPI starts before Streamlit
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
