# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rating-predictor-app-pdp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://marshallmykietyshynpdp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d9458631fbe340efbd1b5cfff81fa59b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_047f897618df4d47bf606c869ff7123a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: marshallmykietyshynpdp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d9458631fbe340efbd1b5cfff81fa59b }}/streamlit:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rating-predictor-app-pdp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0c6be54458c943389490d65216e844e4 }}
        images: 'marshallmykietyshynpdp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d9458631fbe340efbd1b5cfff81fa59b }}/streamlit:${{ github.sha }}'